handwrite --debug-directory ./debug/ --sheet-version 3.0.4               --designer "jan Kinlo Watesa"   --family "sitelen pona pi jan Watesa"      --filename "sitelen pona pi jan Watesa" ./sitelen-pona-pi-jan-Watesa-sin_a.png ./ --license "CC-BY-NC-SA-4.0" --license-url "https://creativecommons.org/licenses/by-nc-sa/4.0/" --other-words "_ a! a_ a? _ san po apeja wuwojiti powe n_ nnn _ -- ni2 ni3 ni4 ni5 ni6 ni7 ni8 aaa am -t a!_"
handwrite --debug-directory ./debug/ --sheet-version 2.0.0 --license cc0 --designer "nasa Topo"          --family "nasin sitelen musi tan nasa Topo" --filename "nasin sitelen musi tan nasa Topo" ./nasin-sitelen-musi-tan-nasa-Topo-sv2.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.2.2 --license cc0 --designer "jan Ketesi"         --family "sitelen Ketesi nasa"             --filename "sitelen Ketesi nasa" ./sitelen-Ketesi-nasa-sv2.2.2.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.2.3 --license ofl --designer "waso Keli"          --family "linja open tan waso Keli"        --filename "linja open tan waso Keli" ./linja-open-tan-waso-Keli-sv2.2.3.png ./ --other-words "a _ _ _ _ _ _ akesi _ _ lape _ _ meso mi moku Keli luka noka _ lukin laso"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license cc0 --designer "ilo Popsie"         --family "sitelen pi suwi nasa tan ilo Popsie" --filename "sitelen pi suwi nasa tan ilo Popsie" ./sitelen-pi-suwi-nasa-tan-ilo-Popsie-sv3.0.0.png ./ --other-words "_ _ _ _ _ kiki ki nele Popsie"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license cc0 --designer "jan Nopu"           --family "sitelen linja tan jan Nopu"      --filename "sitelen linja tan jan Nopu" ./sitelen-linja-tan-jan-Nopu-sv3.0.0.png ./ --other-words "_ namako2/temp_namako_crosshair mama2 majuna2/temp_majuna_lotus _ sewi2/temp_sewi_directional misikeke2/temp_misikeke_bowl mute2/temp_mute_hands toki+pona olin2/temp_olin_regular/temp_olin_overlap isipin mu2/temp_mu_emitters _ kule2/temp_kule_regular uta2/temp_uta_regular ka jaki2 jaki3 ko2 ko3 kiwen2 kokosila soto teje apeja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "akesi Kilo"         --family "sitelen luka Kilo"               --filename "sitelen luka Kilo" ./sitelen-luka-Kilo-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "alesa"              --family "luka pi tenpo lili tan alesa"    --filename "luka pi tenpo lili tan alesa" .\luka-pi-tenpo-lili-tan-alesa-sv3.0.0.png ./ --other-words "_ jan awen ken _ kepeken kute loje mama mi moku pali alesa pimeja _ seme sike sina _ _ _ _ sitelen waso tawa"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Iwi"            --family "sitelen luka ante tan jan Iwi"   --filename "sitelen luka ante tan jan Iwi" ./sitelen-luka-ante-tan-jan-Iwi-sv3.0.0.jpg ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ _ api _ kan _ eliki"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Iwi"            --family "sitelen luka tan jan Iwi"        --filename "sitelen luka tan jan Iwi" ./sitelen-luka-tan-jan-Iwi-sv3.0.0.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Kulusepelipowi" --family "sitelen pi ma Kota Santen"       --filename "sitelen pi ma Kota Santen" ./sitelen-pi-ma-Kota-Santen-sv3.0.0.png ./ --other-words "_ ni4 ni3 ni2 _ owe powe san soto teje juna Kulusepelipowi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "kili Temeke"        --family "kilitelen"                       --filename "kilitelen" ./kilitelen-tan-kili-Temeke-sv3.0.0.png ./ --other-words "_ meli2/temp_meli_venus mije2/temp_mije_mars linuwi _ olin2/temp_olin_emitters mi2 sina2 usawi powe puwa isipin _ pake kili2 jami kiki kulijo oke owe kamalawala sewi2/temp_sewi_directional"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "meli Siliwa"        --family "sitelen meli kule tan meli Siliwa" --filename "sitelen meli kule tan meli Siliwa" ./sitelen-meli-kule-tan-meli-Siliwa-sv3.0.0.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ ka _ _ _ _ _ _ _ Siliwa Stella Majeka"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu"      --family "sitelen pi linja telo tan soweli Selupu" --filename "sitelen pi linja telo tan soweli Selupu" ./sitelen-pi-linja-telo-tan-soweli-Selupu-sv3.0.0.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu"      --family "sitelen soweli linja tan soweli Selupu" --filename "sitelen soweli linja tan soweli Selupu" ./sitelen-soweli-linja-tan-soweli-Selupu-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu"      --family "sitelen sowepipi"                --filename "sitelen sowepipi" ./sitelen-sowepipi-tan-soweli-Selupu-sv3.0.2.png ./ --other-words "_ usawi mijomi melome _ omekapo linluwi2 yupekosi mu2 sowepipi Selupu Linku _ Siliwa Tekinowi Vivi Kolisin Kaken Stella Ipan Teli Lite Molili"
handwrite --debug-directory ./debug/ --sheet-version 3.0.2 --license cc0 --designer "ilo Popsie"         --family "suli lukin tan ilo Popsie"       --filename "suli lukin tan ilo Popsie" ./suli-lukin-tan-ilo-Popsie-sv3.0.2.png ./ --other-words "_ Popsie kiki powe _ jule nele kosan ete su kokosila toki+pona _ usawi isipin san kapesi pake taki puwa pika eliki soto teje alu"
handwrite --debug-directory ./debug/ --sheet-version 3.0.2 --license ofl --designer "kulupu seli"        --family "sitelen seli luka tan kulupu seli" --filename "sitelen seli luka tan kulupu seli" ./sitelen-seli-luka-tan-kulupu-seli-sv3.0.2.png ./ --other-words "_ sewi2/temp_sewi_directional"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license cc0 --designer "jan Mikki"          --family "kisa lili"                       --filename "kisa lili" .\kisa-lili-tan-jan-Mikki-sv3.0.3.png ./ --other-words "_ isipin kiki oke _ wa kisa alu nan pa powe apeja _ pake jami omekapo puwa nja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license ofl --designer "kasi Lija"          --family "kasi linja tan kasi Lija"        --filename "kasi linja tan kasi Lija" ./kasi-linja-tan-kasi-Lija-sv3.0.3.png ./ --other-words "_ _ _ _ _ ni2 ni3 ni4 ni5 ni6 ni7 ni8 _ sewi2/temp_sewi_directional"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license cc0 --designer "pika Tejo"          --family "sitelen kulupu tan pika Tejo"    --filename "sitelen kulupu tan pika Tejo" .\sitelen-kulupu-tan-pika-Tejo.png ./ --other-words "_ epikulijo tejo kijoke _ tejetekone an kjt soto teke kikolo jansoweli _ linuko kamalawala owe kijesankalu lakari na likota ete pika mpptp kekan yupekosi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Nopu"           --family "poka luka tan jan Nopu"          --filename "poka luka tan jan Nopu" ./poka-luka-tan-jan-Nopu-sv3.0.4px.png ./ --other-words "_ namako2/temp_namako_crosshair _ majuna2/temp_majuna_lotus _ sewi2/temp_sewi_directional mi2 sina2 ona2 _ _ mu2/temp_mu_emitters _ misikeke2/temp_misikeke_bowl uta2/temp_uta_regular kokosila soto teje apeja ka kule2/temp_kule_regular" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "Ali Najafi"         --family "jan Ali"                         --filename "jan Ali" .\jan-Ali-sv3.0.4.png ./ --other-words "_ sewi2/temp_sewi_directional mute2/temp_mute_hands _ _ kiki kokosila powe"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Jami"           --family "linja li nja tan jan Jami"       --filename "linja li nja tan jan Jami" ./linja-li-nja-tan-jan-Jami-sv3.0.4.png ./ --other-words "_ Wapa nja amen _ taki kiki puwa powe usawi melome kulijo _ ka nita kepa nula susu isi joku jule asa lanu sala Jami"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Jami"           --family "sitelen jami tan jan jami"       --filename "sitelen jami tan jan jami" .\sitelen-jami-tan-jan-Jami-sv3.0.4.png ./ --other-words "_ _ _ _ _ ka jami Jami"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan luka tu"        --family "sitelen luka tan jan luka tu"    --filename "sitelen luka tan jan luka tu" .\sitelen-luka-tan-jan-luka-tu-sv3.0.4.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan waso Lawen"     --family "sitelen jaso tonsi"              --filename "sitelen jaso tonsi" ./sitelen-jaso-tonsi-tan-jan-waso-Lawen-sv3.0.4.png ./ --other-words "_ mu2 jaki2 ko2 _ apeja eliki jaso namako2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli Siliwa"        --family "loje meli"                       --filename "loje meli" ./loje-meli-tan-meli-Siliwa-sv3.0.4.png ./ --other-words "_ kalma/kamla/kama&kala sitelen&mun sewi2/temp_sewi_directional _ san toki+pona/toki&pona penpo jupi kana me ka _ meliSiliwa usawi Majeka Misi Nemona Sesi Manka Vivi olin+ijo/olin&ijo Kaken Selupu kijesankalu"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli Siliwa"        --family "sitelen Lenluwi"                 --filename "sitelen Lenluwi" sitelen-Lenluwi-tan-meli-Siliwa.png ./ --other-words "_ tonsi2 soko2/soko_annulus epiku2/temp_epiku_emitters _ toki+pona/toki&pona olin+ijo/olin&ijo sitelen&mun o&pan&meli meliSiliwa Lenluwi Sinki _ san ka ote kijesankalu kana penpo Isi jupi Majeka jupi2 Sesi Manka"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli usawi"         --family "sitelen nasa tan meli usawi"     --filename "sitelen nasa tan meli usawi" ./sitelen-nasa-tan-meli-usawi-sv3.0.4.jpg ./ --other-words "_ mije _ _ _ _ _ _ _ _ _ _ _ _ wa _ _ usawi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "linja telo Esi"                  --filename "linja telo Esi" .\linja-telo-Esi-sv3.0.4.png ./ --other-words "_ { } _ _ kokosila nimisin usawi powe wuwojiti kiki apeja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen Esi"                     --filename "sitelen Esi" ./sitelen-Esi-tan-mu-Esitense-usawi-sv3.0.4.png ./ --other-words " _ usawi mu2/temp_mu_emitters nja _ iseki saja san po kiki powe apeja _ mute2/temp_mute_hands aku ete kokosila pata ka jule kalama2/kalamARR yutu nimisin apelo sewi2/temp_sewi_directional"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Keli"          --family "leko majuna sin"                 --filename "leko majuna sin" .\leko-majuna-sin-tan-waso-Keli-sv3.0.4px.png ./ --other-words "_ kiki kokosila usawi _ api Keli melome Pingo penpo poni snoweli _ ka kulijo wasoweli silapa silapa1 silapa2 silapa3 tasun tasun1 tasun2 tasun3 wa" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso musi Ipan"     --family "sitelen Suwekona pi waso leko tan waso musi Ipan" --filename "sitelen Suwekona pi waso leko tan waso musi Ipan" .\sitelen-pi-waso-leko-tan-waso-musi-Ipan-sv3.0.4.png ./ --other-words "_ kon2 mu2 wuwojiti _ wa penpo Stella Majeka Kaken Ipan juna _ kijesankalu kijelu kilu kl kijetetonsikalu ka pilinWen sowepipi kijetejanpakalu yupekosi kulijo"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "soweli lili Mili"   --family "sitelen luka ante tan soweli lili Mili" --filename "sitelen luka ante tan soweli lili Mili" .\sitelen-luka-ante-tan-soweli-lili-Mili-sv3.0.4.png ./ --other-words "_ sewi2/temp_sewi_religious namako2/temp_namako_crosshair kala2/temp_kala_eyes _ aaa jan+pona ma+pona ma+ante pilin+pona pilin+ike pilin+lape _ pilin+nasa sona+ala jan+ante toki+pona kokosila ijo+ante pi+ijo+ante linja2 jan+seme toki+a kama+pona tawa+pona"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mun Kekan San"      --family "sitelen mun tan mun Kekan San"   --filename "sitelen mun tan mun Kekan San" ./sitelen-mun-tan-mun-Kekan-San-sv3.0.4.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ mun jaki2 weka2 sitelen2 sinpin2 monsi2 poka< akesi2 lape2 moli2 kin2 olin2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Sena"           --family "leko seli"                       --filename "leko seli" .\leko-seli-sv3.0.4px.png ./ --other-words "monsi2/temp_monsi_tail poka2 sewi2/temp_sewi_religious anpa2 sinpin2 a2/temp_a_straight o2/temp_o_straight kin2/temp_kin_straight n2/temp_n_straight aaa/temp_a_triple nnn wawa&nasin insa2 kijete1 kijete2 kijete3 kijete4 namako2/temp_namako_pepper kokosila [2 ]2 linuwi2/linluwi2/temp_linluwi_sitelenvariant pan2/temp_pan_regular akesi2/temp_akesi_4_legged/temp_akesi_6_legged Sena" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen leko Esi"                --filename "sitelen leko Esi" ./sitelen-leko-Esi-tan-mu-Esitense-usawi-sv3.0.4px.png ./ --other-words " _ usawi mu2/temp_mu_emitters nja _ iseki saja san po kiki powe apeja _ mute2/temp_mute_hands aku ete kokosila pata ka jule kalama2 yutu nimisin apelo sewi2/temp_sewi_directional" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mun Kekan San"      --family "sitelen mun tan mun Kekan San"   --filename "sitelen mun tan mun Kekan San" .\sitelen-mun-tan-mun-Kekan-San-sv3.0.4.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ mun2 jaki2 weka2 sitelen2 sinpin2 monsi2 poka< akesi2 lape2 moli2 kin2 olin2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Lusi"           --family "musi-leko-tan-jan-Lusi"          musi-leko-14x14-tan-jan-Lusi-v1.4.png ./ --other-words "moli2/temp_moli_regular san po sewi2/temp_sewi_directional _ kokosila pake apeja powe kiki oke usawi _ omekapo wa kamalawala kulijo ko2 seme2/temp_seme_regular soko2/soko_annulus majuna2/temp_majuna_lotus namako2/temp_namako_pepper su2 isipin wile2/temp_wile_heart" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Lusi"           --family "musi-leko-HD-tan-jan-Lusi"       musi-leko-HD-tan-jan-Lusi_v1.1.png ./ --other-words "moli2/temp_moli_regular san po sewi2/temp_sewi_directional _ kokosila pake apeja powe kiki oke usawi _ omekapo wa kamalawala kulijo ko2 seme2/temp_seme_regular soko2/soko_annulus majuna2/temp_majuna_lotus namako2/temp_namako_pepper su2 isipin wile2/temp_wile_heart"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "enky"               --family "doublestruck-tan-enky"           doublestruck-tan-enky.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Nopu"           --family "zqx"                             ./zqx-sv3.0.4.png ./ --other-words "_ mute2/temp_mute_hands sewi2/temp_sewi_directional kokosila _ misikeke2/temp_misikeke_bowl ka kiwen2 mu2/temp_mu_emitters isipin namako2/temp_namako_crosshair owe _ majuna2/temp_majuna_lotus peto juna soto teje toki+pona omekapo apeja ko2 ko3 jaki2 jaki3"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Stella (Winx Club)" --family "sitelen pona lili tan jan Stella" --filename "sitelen-pona-lili-tan-jan-Stella-Winx-Club.ttf" ./Khong_Co_Tieu_e11_20250424181721.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "akesi Sami"         --family "sitelen pona pi akesi Sami"      --filename "sitelen-pona-pi-akesi-Sami" ./sitelen-pona-pi-akesi-Sami-sv3.0.4.png ./ --other-words "_ _ _ _ _ _ _ kokosila pake apeja _ _ _ oke omekapo wekama _ wa nja kulijo _ _ kamalawala usawi Kekansan"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Kamin"          --family "linja Kamin tan jan Kamin"       --filename "linja-kamin-tan-jan-kamin" ./linja-kamin-tan-jan-kamin.jpeg ./ --other-words "_ jaki2 jaki3 senselo _ kensin uwa epiku2 majuna2 mute2 sewi2 toki+pona _ isipin wa kokosila soto teje apeja tenpo2 usawi powe pake jonke Kamin"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "linja Eko tan waso Eko Bold"     --filename "linja-Eko-Bold" ./linja-Eko-Bold.png ./                   --other-words "_ jaki2 jaki3 a2/temp_a_acute _ o2/temp_o_acute n2/temp_n_acute epiku2/temp_epiku_arrow majuna2/temp_majuna_upsidedown sewi2/temp_sewi_directional mute2/temp_mute_hands toki+pona _ isipin mu2/temp_mu_emitters kokosila soto teje apeja tenpo2 kin2/temp_kin_acute kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "linja Eko tan waso Eko Light"    --filename "linja-Eko-Light" ./linja-Eko-Light.png ./                 --other-words "_ jaki2 jaki3 a2/temp_a_acute _ o2/temp_o_acute n2/temp_n_acute epiku2/temp_epiku_arrow majuna2/temp_majuna_upsidedown sewi2/temp_sewi_directional mute2/temp_mute_hands toki+pona _ isipin mu2/temp_mu_emitters kokosila soto teje apeja tenpo2 kin2/temp_kin_acute kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "linja Eko tan waso Eko Medium"   --filename "linja-Eko-Medium" ./linja-Eko-Medium.png ./               --other-words "_ jaki2 jaki3 a2/temp_a_acute _ o2/temp_o_acute n2/temp_n_acute epiku2/temp_epiku_arrow majuna2/temp_majuna_upsidedown sewi2/temp_sewi_directional mute2/temp_mute_hands toki+pona _ isipin mu2/temp_mu_emitters kokosila soto teje apeja tenpo2 kin2/temp_kin_acute kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "linja Eko tan waso Eko"          --filename "linja-Eko-Regular" ./linja-Eko-Regular.png ./             --other-words "_ jaki2 jaki3 a2/temp_a_acute _ o2/temp_o_acute n2/temp_n_acute epiku2/temp_epiku_arrow majuna2/temp_majuna_upsidedown sewi2/temp_sewi_directional mute2/temp_mute_hands toki+pona _ isipin mu2/temp_mu_emitters kokosila soto teje apeja tenpo2 kin2/temp_kin_acute kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "linja Eko tan waso Eko Semi Bold" --filename "linja-Eko-Semi_Bd" ./linja-Eko-Semi_Bd.png ./            --other-words "_ jaki2 jaki3 a2/temp_a_acute _ o2/temp_o_acute n2/temp_n_acute epiku2/temp_epiku_arrow majuna2/temp_majuna_upsidedown sewi2/temp_sewi_directional mute2/temp_mute_hands toki+pona _ isipin mu2/temp_mu_emitters kokosila soto teje apeja tenpo2 kin2/temp_kin_acute kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "linja Eko tan waso Eko Semi Light" --filename "linja-Eko-Semi_Lt" ./linja-Eko-Semi_Lt.png ./           --other-words "_ jaki2 jaki3 a2/temp_a_acute _ o2/temp_o_acute n2/temp_n_acute epiku2/temp_epiku_arrow majuna2/temp_majuna_upsidedown sewi2/temp_sewi_directional mute2/temp_mute_hands toki+pona _ isipin mu2/temp_mu_emitters kokosila soto teje apeja tenpo2 kin2/temp_kin_acute kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "linja Eko tan waso Eko Thin"     --filename "linja-Eko-Thin" ./linja-Eko-Thin.png ./                   --other-words "_ jaki2 jaki3 a2/temp_a_acute _ o2/temp_o_acute n2/temp_n_acute epiku2/temp_epiku_arrow majuna2/temp_majuna_upsidedown sewi2/temp_sewi_directional mute2/temp_mute_hands toki+pona _ isipin mu2/temp_mu_emitters kokosila soto teje apeja tenpo2 kin2/temp_kin_acute kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan pi kili mun"    --family "Lilintawa"                       ./Lilintawa-tan-jan-pi-kili-mun-sv3.0.4.jpeg ./ --other-words "_ _ _ _ _ _ _ _ _ _ owe"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "ijo Kesi"           --family "leko kili tan ijo Kesi"          --filename "leko kili tan ijo Kesi" ./leko-kili-tan-ijo-Kesi-sv3.0.4.png ./ --other-words "_ _ _ _ _ meli2 mije2 sewi2 mute2 sinpin2 monsi2 poka2 _ kokosila yupekosi apeja eliki misikeke2 kiki isipin pake powe Pingo" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Erd"            --family "sitelen Erd"                     --filename "sitelen Erd" ./sitelen-Erd-sv3.0.4.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "akesi Sami en jan Poman" --family "sitelen pona pi lukin Manka" --filename "sitelen pona pi lukin Manka" ./sitelen-pona-pi-lukin-Manka-sv3.0.4px.png ./ --other-words "_ _ _ _ _ _ _ kokosila pake apeja _ _ _ oke omekapo wekama _ wa nja kulijo _ _ kamalawala usawi Kekansan" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Juwan"          --family "sitelen pakala Juwan 1"          --filename "sitelen pakala Juwan 1" .\sitelen-pakala-Juwan-1-sv3.0.4.png ./ --other-words "_ _ _ _ _ wawa weka _ _ _ _ _ _ _ mute2 namako2 linluwi2 sewi2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Juwan"          --family "sitelen pakala Juwan 2"          --filename "sitelen pakala Juwan 2" .\sitelen-pakala-Juwan-2-sv3.0.4.png ./ --other-words "_ ni2 ni3 ni4 _ ku misikeke2 namako2 _ soko2 soko3 kokosila _ pini sewi sewi2 _ linluwi2 lipamanka Keli _ Itan _ _ mun2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Juwan"          --family "sitelen pakala Juwan 3"          --filename "sitelen pakala Juwan 3" .\sitelen-pakala-Juwan-3-sv3.0.4.png ./ --other-words "_ misikeke2 soko2 sewi2 _ _ _ lanpan ku namako2 _ _ _ _ _ _ _ jo o _ _ soweli taso tan waso"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Kiso"           --family "kiwen jelo"                      --filename "kiwen jelo" kiwen-jelo-tan-jan-Kiso-sv3.0.4.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ luwi konwe jume"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "soweli Sopi"        --family "nasin Sopitelen"                 --filename "nasin Sopitelen" nasin-Sopitelen-contrast-sv3.0.4.jpg ./ --other-words "_ alasa anpa insa waso _ jelo meli _ mije _ _ _ mu mun Sopi oko _ _ _ _ _ _ pimeja walo"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Keli"          --family "linja nanpa tu tan waso Keli"    --filename "linja nanpa tu tan waso Keli" linja-nanpa-tu-tan-waso-Keli-contrast-sv3.0.4.jpg ./ --other-words "_ ante mije moli  _ noka _ _ _ _ nasin weka  _ _ _ _ epiku _ selo lukin _ _ a lete kijetesantakalu"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Toluneko"       --family "sitelen Toluneko"                --filename "sitelen Toluneko" sitelen-Toluneko-contrast-sv3.0.4.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "palisa jelo"        --family "palisa jelo"                     --filename "palisa jelo" palisa-jelo-contrast-sv3.0.4.jpg ./ --other-words "_ _ _ _  _ _ _ _ _ _ _ _  _ monsi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "sitelen ko"         --family "sitelen ko"                      --filename "sitelen ko" sitelen-ko-sv3.0.4.jpg ./ --other-words "_ ike la linja  _ nasa leko oko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "pakala Mapuju"      --family "sitelen pi pakala Mapuju"        --filename "sitelen pi pakala Mapuju" sitelen-pi-pakala-Mapuju-sv3.0.4.jpg ./ --other-words "lukin2 _ _ _  monsuta2 alasa e en pu ku kili ko2  _ kule _ mun _ _ open _ toki wawa"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Peton"          --family "sitelen Peton"                   --filename "sitelen Peton" sitelen-Peton-sv3.0.4.jpg ./ --other-words "_ _ _ _  _ _ _ _ _ _ _ _  _ musi len nasa selo leko _ laso"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Kapi"           --family "sitelen pi jan Kapi"             --filename "sitelen pi jan Kapi" sitelen-pi-jan-Kapi-sv3.0.4.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Liwa"           --family "sitelen pona nasa Liwa"          --filename "sitelen pona nasa Liwa" sitelen-pona-nasa-Liwa-sv3.0.4.jpg ./ --other-words "_ i w _  _ monsi _ _ _ _ _ _  _ jasima"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Wiwijen"        --family "sitelen Sijato"                  --filename "sitelen Sijato" sitelen-Sijato-contrast-sv3.0.4.jpg ./ --other-words "_ kapesi semicolon comma  _ wuwojiti unu sutopatikuna pika owe kamalawala epiku  _ exclamationmark questionmark mulapisu nimisin apeja kokosila puwa usawi yupekosi po san misa"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Suko"           --family "sitelen Suko"                    --filename "sitelen Suko" sitelen-Suko-sv3.0.4.jpg ./ --other-words "_ _ _ _  _ _ _ _ _ _ _ _  _ meso epiku"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "soko Sensoko"       --family "sitelen kasi tan soko Senseko"   --filename "sitelen-kasi-tan-soko-Senseko" sitelen-kasi-tan-soko-Senseko-sv3.0.4.png ./ --other-words "_ sen mo Sensoko   _ olapona pulasi losu isuta"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen Esi pona"                --filename "sitelen Esi pona" ./sitelen-Esi-pona-sv3.0.4.png ./ --other-words "_ usawi mu2/temp_mu_emitters/; ana   _ iseki saja san po kiki powe apeja   _ mute2/temp_mute_hands peto ete kokosila unu me jule kijosin yutu soto teje sewi2/temp_sewi_directional"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen akesi Esi"               --filename "sitelen akesi Esi" ./sitelen-akesi-Esi-sv3.0.4.png ./ --other-words "_ doublequote singlequote usawi   _ kokosila mulapisu namako2/temp_namako_pepper majuna2/temp_majuna_lotus yupekosi kule2 moli2/temp_moli_face   _ ana kijosin iseki saja unu jaki1 jaki2 jaki3 jaki4 pu1 pu2 mani2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen Uwi Alu Ewi"             --filename "sitelen Uwi Alu Ewi" ./sitelen-Uwi-Alu-Ewi-sv3.0.4.png ./ --other-words "_ usawi mu2/temp_mu_emitters/; kokosila   _ unu yutu suno2 ete soto teje jaki2   _ namako2/temp_namako_crosshair majuna2/temp_majuna_lotus me ka kal kalam kalamaw kalamawa kalamawal kalamawala kijosin iseki"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "linja olin Esi"                  --filename "linja olin Esi" ./linja-olin-Esi-sv3.0.4.png ./ --other-words "_ usawi iseki ana   _ olin2/temp_olin_emitters siwala jami puwa kulijo mijomi melome   _ fhqwhgads ete suwili jume me kankuli unu taki oke nja mulapisu tonsoton"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "nasin nasin Esi"                 --filename "nasin nasin Esi" ./nasin-nasin-Esi-sv3.0.4.png ./ --other-words "_ kokosila usawi nimisin   _ jaki2 jaki3 ko2 ko3 kiki olin2/temp_olin_emitters sewi2/temp_sewi_directional   _ wile2/temp_wile_heart apeja kala2/temp_kala_eyes uta2/temp_uta_dotless namako2/temp_namako_crosshair majuna2/temp_majuna_upsidedown linluwi2/linuwi2/temp_linluwi_sitelenvariant lanpan2/temp_lanpan_flipped soko2/soko_thinstem soko3/soko_thickstem powe mu2/temp_mu_emitters/;"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen suwi Esi"                --filename "sitelen suwi Esi" ./sitelen-suwi-Esi-sv3.0.4.png ./ --other-words "_ e{ }e me   _ li{ }li { } , ! ?   _ usawi iseki unu pi{ }pi o{ }o a2 e2 o2 kiki apeja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "sike Sapi"          --family "sitelen pona pi sike Sapi"       --filename "sitelen-pona-pi-sike-Sapi" ./sitelen-pona-pi-sike-Sapi-tan-sike-Sapi-v3.0.4.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Mate"           --family "jan Mate"                        --filename "jan-Mate" ./jan-Mate-v3.0.4.png ./ --other-words "_ _ _ _ _ molusa _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Jonatan Lise"   --family "sitelen Sapu Jonatan"            --filename "sitelen-Sapu-Jonatan" ./sitelen-Sapu-Jonatan-tan-jan-Jonatan-Lise-v3.0.4.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ mute2 sewi2 _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan nasa Sewa"      --family "sitelen pi pona ala"             --filename "sitelen-pi-pona-ala" ./sitelen-pi-pona-ala-tan-jan-nasa-Sewa-v3.0.4.png ./ --other-words "_ _ _ _ _ sijelo pana olin _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Kuta"           --family "sitelen nasa a"                  --filename "sitelen-nasa-a" ./sitelen-nasa-a-tan-jan-Kuta-v3.0.4.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Emilo"          --family "sitelen pona Emilo"              --filename "sitelen-pona-Emilo" ./sitelen-pona-Emilo-tan-jan-Emilo-v3.0.4.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Mikali"         --family "SINtelen"                        --filename "SINtelen-tan-jan-Mikali" ./SINtelen-tan-jan-Mikali-v3.0.4.png ./ --other-words "_ ala jaki lawa _ mije pi majuna oko _ , _ _ kijetesantakalu kokosila po san soto teje _ wa seme -- ( )"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Piku"           --family "sitelen g"                       --filename "sitelen-g" ./sitelen-g-tan-jan-Piku-v3.0.4.png ./ --other-words "_ _ _ _ _ apeja kiki ojuta owe yupekosi wuwojiti g _ _ _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Tamalu"         --family "Sitelen Nanpa"                   --filename "Sitelen-Nanpa-tan-jan-Tamalu" ./Sitelen-Nanpa-tan-jan-Tamalu-v3.0.4.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ pipi supa pakala ko _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Ukamika"        --family "linja nasa"                      --filename "linja-nasa-tan-jan-Ukamika" ./linja-nasa-tan-jan-Ukamika-v3.0.4.png ./ --other-words "_ la ale kijetesantakalu _ Aa Ee Oo _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Simo"           --family "sitelen pona pi nasin Italija"   --filename "sitelen-pona-pi-nasin-Italija" ./sitelen-pona-pi-nasin-Italija-tan-jan-Simo-v3.0.4.png ./ --other-words "_ _ _ _ _ e en esun _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Ke Tami + jan Pate + jan Ukamika + jan Jonatan Lise + jan Mikali + jan Simo + jan Nikilase + jan Kasape + jan Tekinowi + jan Sewa + jan Tepo + kon Temasuke + jan Piku + jan Ani + sike Sapi + jan Tamalu + jan Lna + jan Sapina + jan Osin + jan Mateja + jan Simiman + jan Okan + jan Olipija + ijo vivi + jan Emilo + jan Lusi + jan Pako + loje Kija + jan Lin + jan Alonola + jan Sonatan + jan Melisuwi + jan Molisi + jan Leki + jan Lisaki + jan Mila + jan Neli + jan Sowan + kasi Linwe + jan Mate + jan Lewe + jan Masine + jan Lim" --family "sitelen pona Elopa pi ma Sapu" --filename "sitelen-pona-Elopa-pi-ma-Sapu" ./sitelen-kulupu-Elopa-v3.0.4.png ./ --other-words "_ luka kute monsi2 _ pipi pipi2 panlan namako2 waso moli _ _ molusa Pingo _ _ _ _ sewi2 _ ku su snoweli _"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "lawa pi jan Kikili lon tenpo 3 am" --family "sitelen pi kijetesantakalu ike" --filename "sitelen-pi-kijetesantakalu-ike" ./sitelen-pi-kijetesantakalu-ike-tan-lawa-pi-jan-Kikili-lon-tenpo-3-am-v4.0.png ./ --other-words "_ _ _ _ _ kanan (linluwi) isipin sewi2 lanpan2 olin2 moli2 _ lonsi apeja kokosila powe mute2 s1234567 biang _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Tela"        --family "nasin sitelen pi soweli Tela"    --filename "nasin-sitelen-pi-soweli-Tela" ./nasin-sitelen-pi-soweli-Tela-tan-soweli-Tela-v3.0.0.jpg ./ --other-words "_ mute2 olin2 sewi2 _ kala2 usawi ka nja kapesi unu penpo _ puwa linluwi2 meli2 mije2 namako2 apeja powe kokosila oke taki kiki kiki2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso musi Ipan"     --family "lukeson-Mon"                     ./lukeson-Mon-tan-waso-musi-Ipan-v3.0.4.png ./ --other-words "_ ka powe lukeson-Mon _ lukeson pona2 ike2 kiki wuwojiti wasoweli nimisin _ melome mijomi pona3 ike3 lete2 seli2 suli2 lili2 sin2 majuna2 sewi2 anpa2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Sowan"          --family "sitelen luka Sowan"              ./sitelen-luka-Sowan-tan-jan-Sowan-v3.0.4.png ./ --other-words "_ kiki molusa _ _ unu kapesi wa usawi powe apeja pake _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "soweli Tela"        --family "sitelen leko pi soweli Tela"     --filename "sitelen leko pi soweli Tela" .\sitelen-leko-pi-soweli-Tela-sv4.0px.png ./ --other-words "_ mute2 olin2 sewi2   _ kala2 usawi ka nja kapesi unu penpo   _ puwa linluwi2 meli2 mije2 namako2 apeja powe kokosila oke taki kiki kiki2" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli Siliwa"        --family "sitelen Lenluwi pimeja"          --filename "sitelen Lenluwi pimeja" .\sitelen-Lenluwi-pimeja-tan-meli-Siliwa-sv3.0.4.png ./ --other-words "_ sewi2 jupi jule   _ toki+pona olin+ijo sitelen+mun o+pan+meli meliSiliwa Lenluwi Sinki   _ san ka ote kijesankalu kana penpo Isi pamo Majeka josuta Sesi Manka"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "jan San"            --family "sitelen mu tan jan San"          --filename "sitelen mu tan jan San" .\sitelen-mu-tan-jan-San-sv4.0.png ./ --other-words "_ _ _ _   _ _ _ _ _ _ _ _   _ isipin linko kanan apeja ni2 jonke lonsi samolot"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Luna"           --family "sitelen mun"                     --filename "sitelen-mun-tan-jan-Luna" ./sitelen-mun-tan-jan-Luna-v3.0.4.png ./ --other-words "_ mi _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "sitelen musi linja tan waso Eko" --filename "sitelen musi linja tan waso Eko" .\sitelen-musi-linja-tan-waso-Eko-contrast-sv3.0.4.png ./ --other-words "_ monsi2 sinpin2 kepeken2   _ aaa nnn seme2 jaki2 jaki3 jaki4 jaki5   _ ni&ale ko2 ko3 ko4 puwa sewi2 alasa2 mu2 toki+pona jonke Eko Eko2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko"           --family "musi linja suwi tan waso Eko"    --filename "musi linja suwi tan waso Eko" .\musi-linja-suwi-tan-waso-Eko-sv3.0.4.png ./ --other-words "_ _ _ _   _ _ _ _ _ _ _ _   _ su2"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license cc0 --designer "soko sijeni"        --family "linja sin tan soko sijeni"       --filename "linja sin tan soko sijeni" .\linja-sin-tan-soko-sijeni-sv4.0.png ./ --other-words "_ _ _ _   _ yupekosi Pingo mu2 penpo usawi teto misikeke2   _ sewi2 nj owe wa nja sijeni lipamanka kamalawala eliki isipin ka konwe"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen kiki Esi"                --filename "sitelen kiki Esi" .\sitelen-kiki-Esi-sv3.0.4.png ./ --other-words "_ usawi iseki powe   _ soto teje kiki pakola toki+pona sitelen+pona aku   _ apeja san po unu eliki alu jume eki r peto nusun mu2/temp_mu_emitters/;"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license cc0 --designer "jan Wasopimeja"     --family "linja tenpo tan jan Wasopimeja"  --filename "linja tenpo tan jan Wasopimeja" .\linja-tenpo-tan-jan-Wasopimeja-sv4.0.png ./ --other-words "_ _ _ _   _ kana eliki pika puwa"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "kijetesantakalu Nawili" --family "sitelen Sepi"                --filename "sitelen Sepi" .\sitelen-Sepi-sv4.0.png ./ --other-words "alu ke oki oke linluwi2 oke2 oki2 ke2 wa je lo ja teken ta powe kije usawi mu2 psyweli sikako molusa jonke puwa r pake"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "jan juna Jona"      --family "sitelen Jona"                    --filename "sitelen Jona" .\sitelen-Jona-sv4.0.png ./ --other-words "_ juna isipin soto   _ teje"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "pan Nuto"           --family "sitelen pan palo"                --filename "sitelen pan palo" .\sitelen-pan-palo-sv4.0.png ./ --other-words "_ r palo nja   _ waken"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "ko Sosuwa"          --family "leko Sosuwa Po"                  --filename "leko Sosuwa Po" .\leko-Sosuwa-Po-sv4.0px.png ./ --other-words "_ juna nja r _ sewi2 po ni2 yupekosi oke teje soto _ powe taki kiki puwa sutopatikuna ka konwe waken peto ete eliki iseki" --pixel
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "jan Pa"             --family "sitelen linja tan jan Pa"        --filename "sitelen linja tan jan Pa" .\sitelen-linja-tan-jan-Pa-sv4.0.png ./ --other-words "_ A E I   _ J K L M N O P   _ S T U W sewi2 toki+pona powe kapesi kiki soto teje janPa"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "jan Wasopimeja"     --family "linja Wasopimeja jaki"           --filename "linja-Wasopimeja-jaki-tan-jan-Wasopimeja" ./linja-Wasopimeja-jaki-tan-jan-Wasopimeja-v4.0.png ./ --other-words "kala2 pan2 sewi2 sewi3 kijetesantakalu5 suwi2 unpa2 ala2 mani2 kijetesantakalu2 kijetesantakalu3 kijetesantakalu4 kiki2 kipisi2 lanpan2 misikeke2 kana konwe lan etopa jule kiki kuntu pika puwa"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense"        --family "sitelen ante en ijo ona utala Esi" --filename "sitelen-ante-en-ijo-ona-utala-Esi-tan-mu-Esitense" ./sitelen-ante-en-ijo-ona-utala-Esi-tan-mu-Esitense-v3.0.4.png ./ --other-words "mijomi kiki usawi mute2/temp_mute_hands Esi unu mmejl msa ojuta sikelen tp ti melome kijosin wiki jule eki alu ete jume peto nusun san po likujo"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "sitelen insa telo nasa sewi Esi" --filename "sitelen-insa-telo-nasa-sewi-Esi-tan-mu-Esitense-usawi" ./sitelen-insa-telo-nasa-sewi-Esi-tan-mu-Esitense-usawi-v3.0.4.png ./ --other-words "_ kiki usawi mute2/temp_mute_hands mu2/temp_mu_emitters/; tuwan san tutu po me lape2/temp_lape_regular lawa2/temp_lawa_regular suno2 mun unu unu2 seli2/temp_seli_regular jan2/temp_jan_regular suwi2/temp_suwi_regular unpa2/temp_unpa_regular walo2/temp_walo_regular mije2/temp_mije_mars meli2/temp_meli_venus tonsi2/temp_tonsi_regular monsi2/temp_monsi_regular/temp_monsi_tail"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "pan Nuto"           --family "sitelen pan epiku"               --filename "sitelen-pan-epiku-tan-pan-Nuto" ./sitelen-pan-epiku-tan-pan-Nuto-v4.0.png ./ --other-words "_ sewi2 kisa pamo _ r josuta unu powe palo sita mute2 _ moli2 jule ka"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi"  --family "o linja olin jan Esi"            --filename "o-linja-olin-jan-Esi-tan-mu-Esitense-usawi" ./o-linja-olin-jan-Esi-tan-mu-Esitense-usawi-v3.0.4.png ./ --other-words "_ usawi kiki mute2/temp_mute_hands _ mu2/temp_mu_emitters/; * me san po pake powe _ lon2 sama2 tawa2 tan2 kepeken2 ki ki2 sewi2/temp_sewi_directional iseki ojuta omekapo tonsi2"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "jan San"            --family "sitelen nasa tan jan San"        ./sitelen-nasa-tan-jan-San-v4.0.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ isipin linko kanan"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license cc0 --designer "jan Wasopimeja"     --family "linja tenpo"                     --filename "linja-tenpo-tan-jan-Wasopimeja" ./linja-tenpo-tan-jan-Wasopimeja-v4.0.png ./ --other-words "_ _ _ _ _ kana eliki pika puwa"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license cc0 --designer "pan Nuto"           --family "sitelen pi pan Nuto"             ./pan-Nuto-v4.0.png ./ --other-words "_ pali nja r _ kisa losa mipa"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "pan Nuto"           --family "sitelen pan pali"                --filename "sitelen-pan-pali-tan-pan-Nuto" ./sitelen-pan-pali-tan-pan-Nuto-v4.0.png ./ --other-words "_ r palo nja _ waken"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license cc0 --designer "jan Kimeki"         --family "VeryLegibleSP"                   --filename "VeryLegibleSP-tan-jan-Kimeki" ./VeryLegibleSP-tan-jan-Kimeki-v4.0.png ./ --other-words "_ kisa mijomi sita   _ kiju melome apeja isipin kiki eliki josuta   _ juna toki+pona jule ka nele owe uwu iji ki ete usawi mulapisu"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "akesi Jesi"         --family "JCs Font SP"                     --filename "JCs Font SP" .\JCs-font-SP-sv4.0.png ./ --other-words "_ jume Jesi usawi   _ isipin jami powe kiki oke omekapo misa   _ sutopatikuna kamalawala konwe kulijo"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Pikesike"       --family "sitelen pona pi kipisi mute luka luka" --filename "sitelen-pona-pi-kipisi-mute-luka-luka-tan-jan-Pikesike" ./sitelen-pona-pi-kipisi-mute-luka-luka-tan-jan-Pikesike-sv3.0.4.png ./ --other-words "_ kalama2 epiku2 linluwi2   _ linluwi3 namako2 mute2 toki+pona nimisin powe dotdot   _ full ni2 Pikesike usawi nanpa2 nasin2 o2 olin2 sewi2 waso2 waso3 dotdotdot" --pixel
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license ofl --designer "ijo Jewiko"         --family "linja pi ilo suno tan ilo Jewiko" --filename "linja pi ilo suno tan ilo Jewiko" ./linja-pi-ilo-suno-tan-ilo-Jewiko-sv4.0.png ./ --other-words "_ _ _ _ _ kokosila"
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license cc0 --designer "soweli mu"          --family "soweli mu tan soweli mu"         --filename "soweli mu tan soweli mu" .\soweli-mu-tan-soweli-mu-contrast-sv4.0.jpg ./ --other-words "_ _ _ _   _ unu kapesi _ _ pan" 
handwrite --debug-directory ./debug/ --sheet-version 4.0   --license cc0 --designer "pipi Pipitawa"      --family "sitelen pi pipi tawa"            .\sitelen-pi-pipi-tawa-tan-pipi-Pipitawa-sv4.0.png ./ --other-words "_ aa/a2/a01 ee/e2/e01 oo/o2/o01   _ wa nn/n2/n01 pipi2/pipi01 akesi2/temp_akesi_4_legged/temp_akesi_6_legged waso2/waso01 sewi2/temp_sewi_directional seli2/seli01   _ suno2/suno01 linluwi2/temp_linluwi_sitelenvariant"

rem For PowerShell, prepend this: cd C:/Users/Kelly/Documents/GitHub/wasokeli.github.io/sp-font-maker/
rem In Sublime Text, Edit > Sort Lines (F9) to alphabetize
