handwrite --debug-directory ./debug/ --sheet-version 2.0.0               --designer "jan Kinlo Watesa" --filename "sitelen pona pi jan Watesa" ./sitelen-pona-pi-jan-Watesa-sv2.0.0.png ./ --license "CC-BY-NC-SA-4.0" --license-url "https://creativecommons.org/licenses/by-nc-sa/4.0/"
handwrite --debug-directory ./debug/ --sheet-version 2.0.0 --license cc0 --designer "nasa Topo" --filename "nasin sitelen musi tan nasa Topo" ./nasin-sitelen-musi-tan-nasa-Topo-sv2.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.0.0 --license ofl --designer "jan Majeka" --filename "sitelen Majeka pi alasa wan taso" ./sitelen-Majeka-pi-alasa-wan-taso-sv2.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.2.2 --license cc0 --designer "jan Ketesi" --filename "sitelen Ketesi nasa" ./sitelen-Ketesi-nasa-sv2.2.2.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.2.3 --license ofl --designer "waso Keli" --filename "linja open tan waso Keli" ./linja-open-tan-waso-Keli-sv2.2.3.png ./ --other-words "a _ _ _ _ _ _ akesi _ _ lape _ _ meso mi moku Keli luka noka _ lukin laso"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license cc0 --designer "ilo Popsie" --filename "sitelen pi suwi nasa tan ilo Popsie" ./sitelen-pi-suwi-nasa-tan-ilo-Popsie-sv3.0.0.png ./ --other-words "_ _ _ _ _ kiki ki nele Popsie"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license cc0 --designer "jan Nopu" --filename "sitelen linja tan jan Nopu" ./sitelen-linja-tan-jan-Nopu-sv3.0.0.png ./ --other-words "_ namako2 mama2 majuna2 _ sewi2 misikeke2 mute2 toki+pona olin2 isipin mu2 _ kule2 uta2 ka jaki2 jaki3 ko2 ko3 kiwen2 kokosila soto teje apeja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "akesi Kilo" --filename "sitelen luka Kilo" ./sitelen-luka-Kilo-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "alesa" --filename "luka pi tenpo lili tan alesa" .\luka-pi-tenpo-lili-tan-alesa-sv3.0.0.png ./ --other-words "_ jan awen ken _ kepeken kute loje mama mi moku pali alesa pimeja _ seme sike sina _ _ _ _ sitelen waso tawa"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Iwi" --filename "sitelen luka ante tan jan Iwi" ./sitelen-luka-ante-tan-jan-Iwi-sv3.0.0.jpg ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ _ api _ kan _ eliki"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Iwi" --filename "sitelen luka tan jan Iwi" ./sitelen-luka-tan-jan-Iwi-sv3.0.0.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Kulusepelipowi" --filename "sitelen pi ma Kota Santen" ./sitelen-pi-ma-Kota-Santen-sv3.0.0.png ./ --other-words "_ ni4 ni3 ni2 _ owe powe san soto teje juna Kulusepelipowi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "kili Temeke" --filename "kilitelen" ./kilitelen-tan-kili-Temeke-sv3.0.0.png ./ --other-words "_ meli2 mije2 linuwi _ olin2 mi2 sina2 usawi powe puwa isipin _ pake kili2 jami kiki kulijo oke owe kamalawala sewi2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "meli Siliwa" --filename "sitelen meli kule tan meli Siliwa" ./sitelen-meli-kule-tan-meli-Siliwa-sv3.0.0.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ ka _ _ _ _ _ _ _ Siliwa Stella Majeka"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen pi linja lili tan soweli Selupu" ./sitelen-pi-linja-lili-tan-soweli-Selupu-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen pi linja telo tan soweli Selupu" ./sitelen-pi-linja-telo-tan-soweli-Selupu-sv3.0.0.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen soweli linja tan soweli Selupu" ./sitelen-soweli-linja-tan-soweli-Selupu-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen sowepipi" ./sitelen-sowepipi-tan-soweli-Selupu-sv3.0.2.png ./ --other-words "_ usawi mijomi melome _ omekapo linluwi2 yupekosi mu2 sowepipi Selupu Linku _ Siliwa Tekinowi Vivi Kolisin Kaken Stella Ipan Teli Lite Molili"
handwrite --debug-directory ./debug/ --sheet-version 3.0.2 --license cc0 --designer "ilo Popsie" --filename "suli lukin tan ilo Popsie" ./suli-lukin-tan-ilo-Popsie-sv3.0.2.png ./ --other-words ""
handwrite --debug-directory ./debug/ --sheet-version 3.0.2 --license ofl --designer "kulupu seli" --filename "sitelen seli luka tan kulupu seli" ./sitelen-seli-luka-tan-kulupu-seli-sv3.0.2.png ./ --other-words "_ sewi2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license cc0 --designer "jan Mikki" --filename "kisa lili" .\kisa-lili-tan-jan-Mikki-sv3.0.3.png ./ --other-words "_ isipin kiki oke _ wa kisa alu nan pa powe apeja _ pake jami omekapo puwa nja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license ofl --designer "kasi Lija" --filename "kasi linja tan kasi Lija" ./kasi-linja-tan-kasi-Lija-sv3.0.3.png ./ --other-words "_ _ _ _ _ ni2 ni3 ni4 ni5 ni6 ni7 ni8 _ sewi2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Nopu" --filename "poka luka tan jan Nopu" ./poka-luka-tan-jan-Nopu-sv3.0.4px.png ./ --other-words "_ namako2 _ majuna2 _ sewi2 mi2 sina2 ona2 _ _ mu2 _ misikeke2 uta2 kokosila soto teje apeja ka kule2" 
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "Ali Najafi" --filename "jan Ali" .\jan-Ali-sv3.0.4.png ./ --other-words "_ sewi2 mute2 _ _ kiki kokosila powe"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Jami" --filename "linja li nja tan jan Jami" ./linja-li-nja-tan-jan-Jami-sv3.0.4.png ./ --other-words "_ Wapa nja amen _ taki kiki puwa powe usawi melome kulijo _ ka nita kepa nula susu isi joku jule asa lanu sala Jami"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Jami" --filename "sitelen jami tan jan jami" .\sitelen-jami-tan-jan-Jami-sv3.0.4.png ./ --other-words "_ _ _ _ _ ka jami Jami"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan luka tu" --filename "sitelen luka tan jan luka tu" .\sitelen-luka-tan-jan-luka-tu-sv3.0.4.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan waso Lawen" --filename "sitelen jaso tonsi" ./sitelen-jaso-tonsi-tan-jan-waso-Lawen-sv3.0.4.png ./ --other-words "_ mu2 jaki2 ko2 _ apeja eliki jaso namako2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli Siliwa" --filename "loje meli" ./loje-meli-tan-meli-Siliwa-sv3.0.4.png ./ --other-words "_ monsi2 sinpin2 sewi2 _ san jami penpo jupi kana me ka _ meliSiliwa Stella Majeka Misi Nemona Sesimiku Manka Vivi Ipan Kaken Selupu kijesankalu"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli usawi" --filename "sitelen nasa tan meli usawi" ./sitelen-nasa-tan-meli-usawi-sv3.0.4.jpg ./ --other-words "_ mije _ _ _ _ _ _ _ _ _ _ _ _ wa _ _ usawi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi" --filename "linja telo Esi" .\Untitled7_20250102232458.png ./ --other-words "_ { } _ _ kokosila nimisin usawi powe wuwojiti kiki apeja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Keli" --filename "leko majuna sin" .\leko-majuna-sin-tan-waso-Keli-sv3.0.4px.jpg ./ --other-words "_ kiki kokosila usawi _ api Keli melome Pingo penpo poni snoweli _ ka kulijo oke silapa silapa1 silapa2 silapa3 tasun tasun1 tasun2 tasun3 wa"
rem for PowerShell, prepend this: cd C:/Users/Kelly/Documents/GitHub/wasokeli.github.io/sp-font-maker/
rem handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi" --filename "sitelen Esi" ./sitelen-Esi-tan-mu-Esitense-usawi-sv3.0.4.png ./ --other-words " _ usawi mu2 nja _ iseki saja san po kiki powe apeja _ mute2 aku ete kokosila pata ka jule kalama2 yutu nimisin apelo sewi2"
rem in Sublime Text, Edit > Sort Lines (F9) to alphabetize