handwrite --debug-directory ./debug/ --sheet-version 3.0.4               --designer "jan Kinlo Watesa" --filename "sitelen pona pi jan Watesa" ./sitelen-pona-pi-jan-Watesa-sin_a.png ./ --license "CC-BY-NC-SA-4.0" --license-url "https://creativecommons.org/licenses/by-nc-sa/4.0/" --other-words "_ a! a- a? _ san po apeja wuwojiti powe n- nnn _ - ni2 ni3 ni4 ni5 ni6 ni7 ni8 aaa am -t a!-"
handwrite --debug-directory ./debug/ --sheet-version 2.0.0 --license cc0 --designer "nasa Topo" --filename "nasin sitelen musi tan nasa Topo" ./nasin-sitelen-musi-tan-nasa-Topo-sv2.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.0.0 --license ofl --designer "jan Majeka" --filename "sitelen Majeka pi alasa wan taso" ./sitelen-Majeka-pi-alasa-wan-taso-sv2.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.2.2 --license cc0 --designer "jan Ketesi" --filename "sitelen Ketesi nasa" ./sitelen-Ketesi-nasa-sv2.2.2.png ./
handwrite --debug-directory ./debug/ --sheet-version 2.2.3 --license ofl --designer "waso Keli" --filename "linja open tan waso Keli" ./linja-open-tan-waso-Keli-sv2.2.3.png ./ --other-words "a _ _ _ _ _ _ akesi _ _ lape _ _ meso mi moku Keli luka noka _ lukin laso"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license cc0 --designer "ilo Popsie" --filename "sitelen pi suwi nasa tan ilo Popsie" ./sitelen-pi-suwi-nasa-tan-ilo-Popsie-sv3.0.0.png ./ --other-words "_ _ _ _ _ kiki ki nele Popsie"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license cc0 --designer "jan Nopu" --filename "sitelen linja tan jan Nopu" ./sitelen-linja-tan-jan-Nopu-sv3.0.0.png ./ --other-words "_ namako2 mama2 majuna2 _ sewi2 misikeke2 mute2 toki+pona olin2 isipin mu2 _ kule2 uta2 ka jaki2 jaki3 ko2 ko3 kiwen2 kokosila soto teje apeja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "akesi Kilo" --filename "sitelen luka Kilo" ./sitelen-luka-Kilo-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "alesa" --filename "luka pi tenpo lili tan alesa" .\luka-pi-tenpo-lili-tan-alesa-sv3.0.0.png ./ --other-words "_ jan awen ken _ kepeken kute loje mama mi moku pali alesa pimeja _ seme sike sina _ _ _ _ sitelen waso tawa"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Iwi" --filename "sitelen luka ante tan jan Iwi" ./sitelen-luka-ante-tan-jan-Iwi-sv3.0.0.jpg ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ _ api _ kan _ eliki"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Iwi" --filename "sitelen luka tan jan Iwi" ./sitelen-luka-tan-jan-Iwi-sv3.0.0.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "jan Kulusepelipowi" --filename "sitelen pi ma Kota Santen" ./sitelen-pi-ma-Kota-Santen-sv3.0.0.png ./ --other-words "_ ni4 ni3 ni2 _ owe powe san soto teje juna Kulusepelipowi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "kili Temeke" --filename "kilitelen" ./kilitelen-tan-kili-Temeke-sv3.0.0.png ./ --other-words "_ meli2 mije2 linuwi _ olin2 mi2 sina2 usawi powe puwa isipin _ pake kili2 jami kiki kulijo oke owe kamalawala sewi2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "meli Siliwa" --filename "sitelen meli kule tan meli Siliwa" ./sitelen-meli-kule-tan-meli-Siliwa-sv3.0.0.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ ka _ _ _ _ _ _ _ Siliwa Stella Majeka"
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen pi linja lili tan soweli Selupu" ./sitelen-pi-linja-lili-tan-soweli-Selupu-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen pi linja telo tan soweli Selupu" ./sitelen-pi-linja-telo-tan-soweli-Selupu-sv3.0.0.jpg ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen soweli linja tan soweli Selupu" ./sitelen-soweli-linja-tan-soweli-Selupu-sv3.0.0.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.0 --license ofl --designer "soweli Selupu" --filename "sitelen sowepipi" ./sitelen-sowepipi-tan-soweli-Selupu-sv3.0.2.png ./ --other-words "_ usawi mijomi melome _ omekapo linluwi2 yupekosi mu2 sowepipi Selupu Linku _ Siliwa Tekinowi Vivi Kolisin Kaken Stella Ipan Teli Lite Molili"
handwrite --debug-directory ./debug/ --sheet-version 3.0.2 --license cc0 --designer "ilo Popsie" --filename "suli lukin tan ilo Popsie" ./suli-lukin-tan-ilo-Popsie-sv3.0.2.png ./ --other-words "_ Popsie kiki powe _ jule nele kosan ete su kokosila toki+pona _ usawi isipin san kapesi pake taki puwa pika eliki soto teje alu"
handwrite --debug-directory ./debug/ --sheet-version 3.0.2 --license ofl --designer "kulupu seli" --filename "sitelen seli luka tan kulupu seli" ./sitelen-seli-luka-tan-kulupu-seli-sv3.0.2.png ./ --other-words "_ sewi2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license cc0 --designer "jan Mikki" --filename "kisa lili" .\kisa-lili-tan-jan-Mikki-sv3.0.3.png ./ --other-words "_ isipin kiki oke _ wa kisa alu nan pa powe apeja _ pake jami omekapo puwa nja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license ofl --designer "kasi Lija" --filename "kasi linja tan kasi Lija" ./kasi-linja-tan-kasi-Lija-sv3.0.3.png ./ --other-words "_ _ _ _ _ ni2 ni3 ni4 ni5 ni6 ni7 ni8 _ sewi2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.3 --license cc0 --designer "pika Tejo" --filename "sitelen kulupu tan pika Tejo" .\sitelen-kulupu-tan-pika-Tejo.png ./ --other-words "_ epikulijo tejo kijoke _ tejetekone an kjt soto teke kikolo jansoweli _ linuko kamalawala owe kijesankalu lakari na likota ete pika mpptp kekan yupekosi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Nopu" --filename "poka luka tan jan Nopu" ./poka-luka-tan-jan-Nopu-sv3.0.4px.png ./ --other-words "_ namako2 _ majuna2 _ sewi2 mi2 sina2 ona2 _ _ mu2 _ misikeke2 uta2 kokosila soto teje apeja ka kule2" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "Ali Najafi" --filename "jan Ali" .\jan-Ali-sv3.0.4.png ./ --other-words "_ sewi2 mute2 _ _ kiki kokosila powe"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Jami" --filename "linja li nja tan jan Jami" ./linja-li-nja-tan-jan-Jami-sv3.0.4.png ./ --other-words "_ Wapa nja amen _ taki kiki puwa powe usawi melome kulijo _ ka nita kepa nula susu isi joku jule asa lanu sala Jami"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Jami" --filename "sitelen jami tan jan jami" .\sitelen-jami-tan-jan-Jami-sv3.0.4.png ./ --other-words "_ _ _ _ _ ka jami Jami"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan luka tu" --filename "sitelen luka tan jan luka tu" .\sitelen-luka-tan-jan-luka-tu-sv3.0.4.png ./
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan waso Lawen" --filename "sitelen jaso tonsi" ./sitelen-jaso-tonsi-tan-jan-waso-Lawen-sv3.0.4.png ./ --other-words "_ mu2 jaki2 ko2 _ apeja eliki jaso namako2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli Siliwa" --filename "loje meli" ./loje-meli-tan-meli-Siliwa-sv3.0.4.png ./ --other-words "_ kalma sitelen-mun sewi2 _ san toki-pona penpo jupi kana me ka _ meliSiliwa usawi Majeka Misi Nemona Sesi Manka Vivi olin-ijo Kaken Selupu kijesankalu"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli Siliwa" --filename "sitelen Lenluwi" sitelen-Lenluwi-tan-meli-Siliwa.png ./ --other-words "_ tonsi2 soko2 epiku2 _ toki+pona olin+ijo sitelen+mun o+pan+meli meliSiliwa Lenluwi Sinki _ san ka ote kijesankalu kana penpo Isi jupi Majeka jupi2 Sesi Manka"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "meli usawi" --filename "sitelen nasa tan meli usawi" ./sitelen-nasa-tan-meli-usawi-sv3.0.4.jpg ./ --other-words "_ mije _ _ _ _ _ _ _ _ _ _ _ _ wa _ _ usawi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi" --filename "linja telo Esi" .\Untitled7_20250102232458.png ./ --other-words "_ { } _ _ kokosila nimisin usawi powe wuwojiti kiki apeja"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Keli" --filename "leko majuna sin" .\leko-majuna-sin-tan-waso-Keli-sv3.0.4px.png ./ --other-words "_ kiki kokosila usawi _ api Keli melome Pingo penpo poni snoweli _ ka kulijo oke silapa silapa1 silapa2 silapa3 tasun tasun1 tasun2 tasun3 wa" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso musi Ipan" --filename "sitelen Suwekona pi waso leko tan waso musi Ipan" .\sitelen-pi-waso-leko-tan-waso-musi-Ipan-sv3.0.4.png ./ --other-words "_ kon2 mu2 wuwojiti _ wa penpo Stella Majeka Kaken Ipan juna kijesankalu kijelu kilu kl kijetetonsikalu ka pilinWen sowepipi kijetejanpakalu yupekosi kulijo"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "soweli lili Mili" --filename "sitelen luka ante tan soweli lili Mili" .\sitelen-luka-ante-tan-soweli-lili-Mili-sv3.0.4.png ./ --other-words "_ sewi2 namako2 kala2 _ aaa jan+pona ma+pona ma+ante pilin+pona pilin+ike pilin+lape _ pilin+nasa sona+ala jan+ante toki+pona kokosila ijo+ante pi+ijo+ante linja2 jan+seme toki+a kama+pona tawa+pona"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Sepi" --filename "tomo toki nasa tan jan Sepi" .\tomo-toki-nasa-tan-jan-Sepi-sv3.0.4.png ./ --other-words "_ semikolon _ _ _ jitin _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "ijo Sepi" --filename "sitelen Psyweli" sitelen-Psyweli-tan-ijo-Sepi.png ./ --other-words "_ namako2 namako3 soko2 _ soko3 psyweli psyweli2 nowi kana jule inta _ epiku2 epiku3 anta aku ta ja lo ki wi ulu ata a2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "ijo seme Sepi" --filename "sitelen linja musi" sitelen-linja-musi-tan-ijo-seme-Sepi.png ./ --other-words "psyweli apeja isipin kamalawala psyweli2 kapesi kiki kulijo misa mulapisu oke pake su2 po powe san soto sunopatikana taki teje unu usawi wa wasoweli yupekosi"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mun Kekan San" --filename "sitelen mun tan mun Kekan San" ./sitelen-mun-tan-mun-Kekan-San-sv3.0.4.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ mun jaki2 weka2 sitelen2 sinpin2 monsi2 poka< akesi2 lape2 moli2 kin2 olin2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Sena" --filename "leko seli" .\leko-seli-sv3.0.4px.png ./ --other-words "monsi2 poka2 sewi2 anpa2 sinpin2 a2 o2 kin2 n2 aaa nnn ni2 insa2 kijete1 kijete2 kijete3 kijete4 namako2 kokosila [2 ]2 linuwi2 pan2 akesi2 Sena" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi" --filename "sitelen leko Esi" ./sitelen-leko-Esi-tan-mu-Esitense-usawi-sv3.0.4.png ./ --other-words " _ usawi mu2 nja _ iseki saja san po kiki powe apeja _ mute2 aku ete kokosila pata ka jule kalama2 yutu nimisin apelo sewi2" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mun Kekan San" --filename "sitelen mun tan mun Kekan San" .\sitelen-mun-tan-mun-Kekan-San-sv3.0.4.png ./ --other-words "_ _ _ _ _ _ _ _ _ _ _ _ _ mun2 jaki2 weka2 sitelen2 sinpin2 monsi2 poka< akesi2 lape2 moli2 kin2 olin2"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Lusi" --filename "sitelen pona 14x14 tan jan Lusi" ./sitelen-pona-14x14-tan-jan-Lusi-sv3.0.4px.png ./ --other-words "_ san po sewi2 _ kokosila pake apeja powe kiki oke usawi _ omekapo wa kamalawala kulijo" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Nopu" --filename "zqx" ./zqx-sv3.0.4.png ./ --other-words "_ mute2 sewi2 kokosila _ misikeke2 ka kiwen2 mu2 isipin namako2 owe _ majuna2 peto juna soto teje toki+pona omekapo apeja ko2 ko3 jaki2 jaki3"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license cc0 --designer "jan Stella (Winx Club)" --filename "sitelen-pona-lili-tan-jan-Stella-Winx-Club.ttf" ./Khong_Co_Tieu_e11_20250424181721.png ./ --family "sitelen pona lili tan jan Stella"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "akesi Sami" --filename "sitelen-pona-pi-akesi-Sami.ttf" ./IMG_5542.png ./ --other-words "_ _ _ _ _ _ _ kokosila pake apeja _ _ _ oke omekapo wekama _ wa nja kulijo _ _ kamalawala usawi Kekansan" --pixel
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-eko-tan-waso-eko.ttf" ./linja-eko-tan-waso-eko.png ./ --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 usawi kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan Kamin" --filename "linja-kamin-tan-jan-kamin.ttf" ./linja-kamin-tan-jan-kamin.jpeg ./ --other-words "_ jaki2 jaki3 senselo _ kensin uwa epiku2 majuna2 mute2 sewi2 toki+pona _ isipin wa kokosila soto teje apeja tenpo2 usawi powe pake jonke Kamin"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-Eko-Bold.ttf" ./linja-Eko-Bold.png ./ --family "linja Eko tan waso Eko Bold" --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 kin2 kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-Eko-Light.ttf" ./linja-Eko-Light.png ./ --family "linja Eko tan waso Eko Light" --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 kin2 kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-Eko-Medium.ttf" ./linja-Eko-Medium.png ./ --family "linja Eko tan waso Eko Medium" --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 kin2 kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-Eko-Regular.ttf" ./linja-Eko-Regular.png ./ --family "linja Eko tan waso Eko" --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 kin2 kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-Eko-Semi_Bd.ttf" ./linja-Eko-Semi_Bd.png ./ --family "linja Eko tan waso Eko Semi Bold" --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 kin2 kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-Eko-Semi_Lt.ttf" ./linja-Eko-Semi_Lt.png ./ --family "linja Eko tan waso Eko Semi Light" --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 kin2 kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "waso Eko" --filename "linja-Eko-Thin.ttf" ./linja-Eko-Thin.png ./ --family "linja Eko tan waso Eko Thin" --other-words "_ jaki2 jaki3 a2 _ o2 n2 epiku2 majuna2 sewi2 mute2 toki+pona _ isipin mu2 kokosila soto teje apeja tenpo2 kin2 kiki powe pake Eko"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "jan pi kili mun" --filename "Lilintawa" ./Lilintawa-tan-jan-pi-kili-mun-sv3.0.4.jpeg ./ --other-words "_ _ _ _ _ _ _ _ _ _ owe"
handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "ijo Kesi" --filename "leko kili tan ijo Kesi" ./leko-kili-tan-ijo-Kesi-sv3.0.4.png ./ --other-words "_ _ _ _ _ meli2 mije2 sewi2 mute2 sinpin2 monsi2 poka2 _ kokosila yupekosi apeja eliki misikeke2 kiki isipin pake powe Pingo" --pixel
rem for PowerShell, prepend this: cd C:/Users/Kelly/Documents/GitHub/wasokeli.github.io/sp-font-maker/
rem handwrite --debug-directory ./debug/ --sheet-version 3.0.4 --license ofl --designer "mu Esitense usawi" --filename "sitelen Esi" ./sitelen-Esi-tan-mu-Esitense-usawi-sv3.0.4.png ./ --other-words " _ usawi mu2 nja _ iseki saja san po kiki powe apeja _ mute2 aku ete kokosila pata ka jule kalama2 yutu nimisin apelo sewi2"
rem in Sublime Text, Edit > Sort Lines (F9) to alphabetize
